services:
  - type: web
    name: scrap-sathi-chatbot
    env: docker  # ⬅️ This is the most important line
    region: oregon
    plan: free
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
