services:
  - type: web
    name: scrap-sathi-chatbot
    env: docker  # ← THIS IS CRITICAL!
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8000
